name: 'Events GeoJSON rewrite'
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 * * */1 *'
jobs:
  rewrite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - run: gradle build
    - name: Commit report
      run: |
          git config --global user.name 'Code for Leipzig Robot'
          git config --global user.email 'leipbotnik@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Update geojson" || true
          git push || true
